### PR TITLE
Feature/like dislike buttons

### PR DESCRIPTION
**Pull request by IronChariot**
### Tenno.tv Pull Request

---

**What I did:**
Added code to dependencies and player controls to add 'like' and 'dislike' buttons above videos which use Youtube's API. Added like and dislike buttons to the controls partial, and some styling for the buttons to the styles css file.

---
**Why I did it:**
So that users can authorise and put a rating against a video they are watching without having to go to Youtube.

---
**Fixes issue (include link):**
NA

---
**Mockups, screenshots, evidence:**
Demoed to Xeno.

---

**Was this an issue fix or a suggestion fulfillment?**
Suggestion fulfillment

### CODE REVIEW

**Comment by TobiTenno** [comment]
i'm assuming that since it uses tenno.tv as the callback, it doesn't work from the deployment, right?

**Comment by TobiTenno** [comment]
also, whenever you get the chance to fix up the stuff codacy pointed out for the spaces/tabs mixing, i'd greatly appreciate it.

**Comment by IronChariot** [comment]
Yes, if you want to run it locally and have the like button work, you'll
have to change it from tenno.tv to localhost:3000

As for Codacy Bot's fixes, a lot of them are related to the hello.js
library, so I'll see if I can load that in via a url instead of including
it in the code, now that I know it works. That should cut down most things
Codacy Bot said, and I'll deal with the ones related to my actual code.

**Comment by TobiTenno** [comment]
@IronChariot sorry I haven't done it yet, i'm planning on scoping out some time for this weekend... sorry!

**Pull request merged**
